run: build
	dotnet run -p src/csharp/LetsShop/LetsShop.Basket.WebApi.csproj
	
unit-tests: 
	dotnet test src/test/LetsShop.Basket.Domain.Tests/LetsShop.Basket.Domain.Tests.csproj
	
integration-tests: 
	dotnet test src/test/LetsShop.Basket.IntegrationTests/LetsShop.Basket.IntegrationTests.csproj
	
all-tests: unit-tests integration-tests
	
build:
	dotnet build ./
